### ISSUE TITLE
[Request] Remove "Playing: " and "On: " labels

### ISSUE THREAD

**Issue by bwaredapenguin** [OhhLoz/Rocksmith-Discord-Rich-Presence#8]
The space in which the rich presence is seen is so small, especially with the album cover image, that these labels take up valuable character space that would be better served given to the song and album values themselves. I think the data is implicit/obvious enough that they really don't have much benefit. Speaking of the output data, I'd love to see the accuracy percentage on the same line as the timer.

**Comment by OhhLoz** [comment]
Closed as included in release version 2.1
